/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Q7RouteImport } from './routes/q7'
import { Route as Q6RouteImport } from './routes/q6'
import { Route as Q5RouteImport } from './routes/q5'
import { Route as Q4RouteImport } from './routes/q4'
import { Route as Q3RouteImport } from './routes/q3'
import { Route as Q2RouteImport } from './routes/q2'
import { Route as Q1RouteImport } from './routes/q1'
import { Route as IndexRouteImport } from './routes/index'

const Q7Route = Q7RouteImport.update({
  id: '/q7',
  path: '/q7',
  getParentRoute: () => rootRouteImport,
} as any)
const Q6Route = Q6RouteImport.update({
  id: '/q6',
  path: '/q6',
  getParentRoute: () => rootRouteImport,
} as any)
const Q5Route = Q5RouteImport.update({
  id: '/q5',
  path: '/q5',
  getParentRoute: () => rootRouteImport,
} as any)
const Q4Route = Q4RouteImport.update({
  id: '/q4',
  path: '/q4',
  getParentRoute: () => rootRouteImport,
} as any)
const Q3Route = Q3RouteImport.update({
  id: '/q3',
  path: '/q3',
  getParentRoute: () => rootRouteImport,
} as any)
const Q2Route = Q2RouteImport.update({
  id: '/q2',
  path: '/q2',
  getParentRoute: () => rootRouteImport,
} as any)
const Q1Route = Q1RouteImport.update({
  id: '/q1',
  path: '/q1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/q1': typeof Q1Route
  '/q2': typeof Q2Route
  '/q3': typeof Q3Route
  '/q4': typeof Q4Route
  '/q5': typeof Q5Route
  '/q6': typeof Q6Route
  '/q7': typeof Q7Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/q1': typeof Q1Route
  '/q2': typeof Q2Route
  '/q3': typeof Q3Route
  '/q4': typeof Q4Route
  '/q5': typeof Q5Route
  '/q6': typeof Q6Route
  '/q7': typeof Q7Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/q1': typeof Q1Route
  '/q2': typeof Q2Route
  '/q3': typeof Q3Route
  '/q4': typeof Q4Route
  '/q5': typeof Q5Route
  '/q6': typeof Q6Route
  '/q7': typeof Q7Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/q1' | '/q2' | '/q3' | '/q4' | '/q5' | '/q6' | '/q7'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/q1' | '/q2' | '/q3' | '/q4' | '/q5' | '/q6' | '/q7'
  id: '__root__' | '/' | '/q1' | '/q2' | '/q3' | '/q4' | '/q5' | '/q6' | '/q7'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Q1Route: typeof Q1Route
  Q2Route: typeof Q2Route
  Q3Route: typeof Q3Route
  Q4Route: typeof Q4Route
  Q5Route: typeof Q5Route
  Q6Route: typeof Q6Route
  Q7Route: typeof Q7Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/q7': {
      id: '/q7'
      path: '/q7'
      fullPath: '/q7'
      preLoaderRoute: typeof Q7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q6': {
      id: '/q6'
      path: '/q6'
      fullPath: '/q6'
      preLoaderRoute: typeof Q6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q5': {
      id: '/q5'
      path: '/q5'
      fullPath: '/q5'
      preLoaderRoute: typeof Q5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q4': {
      id: '/q4'
      path: '/q4'
      fullPath: '/q4'
      preLoaderRoute: typeof Q4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q3': {
      id: '/q3'
      path: '/q3'
      fullPath: '/q3'
      preLoaderRoute: typeof Q3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q2': {
      id: '/q2'
      path: '/q2'
      fullPath: '/q2'
      preLoaderRoute: typeof Q2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q1': {
      id: '/q1'
      path: '/q1'
      fullPath: '/q1'
      preLoaderRoute: typeof Q1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Q1Route: Q1Route,
  Q2Route: Q2Route,
  Q3Route: Q3Route,
  Q4Route: Q4Route,
  Q5Route: Q5Route,
  Q6Route: Q6Route,
  Q7Route: Q7Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
